// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-Z5iK_z-lwr8btRsX2SGAv6kBu_HKDpY',
    appId: '1:636604630262:web:639f61c69a85e03f0998d7',
    messagingSenderId: '636604630262',
    projectId: 'habittracker-group1',
    authDomain: 'habittracker-group1.firebaseapp.com',
    storageBucket: 'habittracker-group1.firebasestorage.app',
    measurementId: 'G-7T62DNJVR8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLLdrSg6QN_I8tanVVKML-Fr9Qyw49hlc',
    appId: '1:636604630262:android:20057373a254bed00998d7',
    messagingSenderId: '636604630262',
    projectId: 'habittracker-group1',
    storageBucket: 'habittracker-group1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0i4J68JglKSplpo22xfXjl4cU9VAtCc4',
    appId: '1:636604630262:ios:18c8d1625f05f0570998d7',
    messagingSenderId: '636604630262',
    projectId: 'habittracker-group1',
    storageBucket: 'habittracker-group1.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0i4J68JglKSplpo22xfXjl4cU9VAtCc4',
    appId: '1:636604630262:ios:18c8d1625f05f0570998d7',
    messagingSenderId: '636604630262',
    projectId: 'habittracker-group1',
    storageBucket: 'habittracker-group1.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-Z5iK_z-lwr8btRsX2SGAv6kBu_HKDpY',
    appId: '1:636604630262:web:d083af3400db35020998d7',
    messagingSenderId: '636604630262',
    projectId: 'habittracker-group1',
    authDomain: 'habittracker-group1.firebaseapp.com',
    storageBucket: 'habittracker-group1.firebasestorage.app',
    measurementId: 'G-GJLH0M2VKT',
  );

}